#!/usr/bin/env node
/**
 * Bundles the pipeline Worker into a single, self-contained CLASSIC (non-module) script.
 *
 * @mediapipe/tasks-vision loads its WASM glue via importScripts(), which browsers disallow
 * calling inside a module Worker — see the comment in src/main.ts and
 * google-ai-edge/mediapipe#5257/#5479/#5527. Vite's `new Worker(new URL(...))` dev pipeline also
 * always serves worker code as ESM regardless of the `type` option passed to the Worker
 * constructor, so a classic worker fails differently in dev ("Cannot use import statement
 * outside a module"). Pre-bundling with esbuild into an import-free IIFE and loading it via a
 * plain static URL sidesteps both problems: the browser gets one script with no `import`
 * statements to reject, and MediaPipe's own runtime importScripts() call works because the
 * *final* worker context is genuinely classic.
 *
 * Output goes to public/generated/ (gitignored, regenerated by this script — see
 * fetch-mediapipe-assets.mjs for the same pattern with the MediaPipe assets themselves), served
 * by viteRawStaticAssets.ts like every other file under public/.
 */
import { existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const __dirname = dirname(fileURLToPath(import.meta.url));
const entryPoint = join(__dirname, "..", "src", "worker", "pipeline.worker.ts");
const outDir = join(__dirname, "..", "public", "generated");
const outfile = join(outDir, "pipeline.worker.js");

const watch = process.argv.includes("--watch");

if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

const buildOptions = {
  entryPoints: [entryPoint],
  outfile,
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2022",
  sourcemap: true,
  logLevel: "info",
};

if (watch) {
  const ctx = await esbuild.context(buildOptions);
  await ctx.watch();
  console.log("Watching pipeline.worker.ts for changes...");
} else {
  await esbuild.build(buildOptions);
  console.log(`Built ${outfile}`);
}
